### ISSUE TITLE
[REMOVE] Story: Create a route that doesn't have a dynamic path (manual page)

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/clinical-trials-listing-app#10]
## As a [role], I want [feature], so that [benefit]

Put it in as the / route instead of disease or intervention. The / route should expect that someone has provided a clinical trials search API query as part of the initialize configuration.

> **ESTIMATE** 3 / 5

### Acceptance Criteria

```gherkin
Scenario: [title]
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

**Comment by sarinapadilla** [comment]
This story has been broken into tasks for the dynamic and manual listing page routing spike.
