### ISSUE TITLE
Delighter is not showing up on IE for Disease and Invention DTLPs.

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/clinical-trials-listing-app#119]
### Issue description
Delighter is not showing up on IE for Disease and Invention DTLPs.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  On IE, go to https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-118/breast-cancer?cfg=0
2. The delighter is not appearing on the page.

### What's the expected result?
- The delighter should be showing up on all Disease and Intervention DTLPs on all browsers including IE.

### What's the actual result?
-  The delighter is NOT showing up for Disease and Intervention DTLPs on IE.

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by VictoriaSunNIH** [comment]
Closing as resolved by #107
