### ISSUE TITLE
Delighter is being displayed on Page Not Found page

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/clinical-trials-listing-app#124]
### Issue description

We are seeing delighters on Page Not Found page. 
Example urls:
https://www-test-acsf.cancer.gov/about-cancer/treatment/clinical-trials/disease/notrials?p1=C123455
https://www-test-acsf.cancer.gov/about-cancer/treatment/clinical-trials/disease/notrials?p1=chicken-nuggets
https://www-test-acsf.cancer.gov/about-cancer/treatment/clinical-trials/disease/C123455

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Go to https://www-test-acsf.cancer.gov/about-cancer/treatment/clinical-trials/disease/notrials?p1=C123455
2. The delighter appears on the page

### What's the expected result?
- TBD (cc: @VictoriaSunNIH )

### What's the actual result?
- The delighter is displayed on Page Not Found page.

CC: @VictoriaSunNIH , @KateMashkinaNIH 

### Additional details / screenshot
![image](https://user-images.githubusercontent.com/28455973/124948839-0fc1eb00-dfdf-11eb-852d-58888cf4323e.png)
### Related Tickets
* Issue #9999
* Issue #9999

**Comment by sarinapadilla** [comment]
This is a cgov-digital-platform issue, as the delighter URLs are set there. Closing this ticket.
