### ISSUE TITLE
On IE, clicking browser back button takes us to Page Not Found for DLP and to a Mini landing page for MLP

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/clinical-trials-listing-app#125]
### Issue description

On IE, when we click a trial link on a DLP and then when the Trial Description page is loaded and we click the browser back button - the user is navigated to the url with a missing part of a path ( e.g.  https://www-test-acsf.cancer.gov/about-cancer/treatment/clinical-trials/disease/breast-cancer/treatment will go back to https://www-test-acsf.cancer.gov/about-cancer/treatment/clinical-trials/disease/breast-cancer  and https://www-test-acsf.cancer.gov/about-cancer/treatment/clinical-trials/disease/breast-cancer to https://www-test-acsf.cancer.gov/about-cancer/treatment/clinical-trials/disease
Also,  when we click a trial link on a MLP and then when the Trial Description page is loaded and we click the browser back button we get back to a Mini Landing page instead of the MLP we started with. 

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  On IE, go to https://www-test-acsf.cancer.gov/about-cancer/treatment/clinical-trials/disease/breast-cancer
2. Click any trial link on the DTLP
3. After the Trial Description page is fully loaded, click the browser back button 
4. We are getting back to Page Not Found page with url https://www-test-acsf.cancer.gov/about-cancer/treatment/clinical-trials/disease/
5. On IE, go to https://www-test-acsf.cancer.gov/about-cancer/treatment/clinical-trials/covid-19
6. Click any trial link on the MLP
7. After the Trial Description page is fully loaded, click the browser back button 
8. We are getting back to the Mini Landing page with url https://www-test-acsf.cancer.gov/about-cancer/treatment/clinical-trials

### What's the expected result?
- For DLP, we should get back to the DLP https://www-test-acsf.cancer.gov/about-cancer/treatment/clinical-trials/disease/breast-cancer and to the same position we have been when we clicked the trial link on this DLP
- For MLP, we should get back to the MLP https://www-test-acsf.cancer.gov/about-cancer/treatment/clinical-trials/covid-19 and to the same position we have been when we clicked the trial link on this MLP

### What's the actual result?
-For DLP, we are getting back to Page Not Found page with url https://www-test-acsf.cancer.gov/about-cancer/treatment/clinical-trials/disease
- For MLP, we are getting back to Mini Landing Page with url https://www-test-acsf.cancer.gov/about-cancer/treatment/clinical-trials

### Additional details / screenshot
-![image](https://user-images.githubusercontent.com/28455973/124980380-4ceba480-e002-11eb-844e-c5698be2723a.png)

### Related Tickets
* Issue #9999
* Issue #9999

cc: @VictoriaSunNIH , @seyilonge-nci , @KateMashkinaNIH , @mworrest

**Comment by sarinapadilla** [comment]
We no longer support IE, so closing this ticket.
