### ISSUE TITLE
Update DLPs to use CTS V2 API

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/clinical-trials-listing-app#126]
We need to update DLPs to use the CTS V2 API.

Attaching the mappings provided by CTRP 

- [CancerGov CTS Calls_Updated Jan 4 2020_v2mappings.pdf](https://github.com/NCIOCPL/clinical-trials-listing-app/files/6886176/CancerGov.CTS.Calls_Updated.Jan.4.2020_v2mappings.pdf)
- [Cancergov - CTS API mappings 2021-06-22.pptx](https://github.com/NCIOCPL/clinical-trials-listing-app/files/6886177/Cancergov.-.CTS.API.mappings.2021-06-22.pptx)

Changes can also be found documented here: https://clinicaltrialsapi.cancer.gov/doc

**Comment by bryanpizzillo** [comment]
This was closed in PR #138

**Comment by sarinapadilla** [comment]
Closing this ticket as the update to CTS API v2 has been launched.
