### ISSUE TITLE
Need to update a param in the url in the link title of Listing Pages

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/clinical-trials-listing-app#128]
### Issue description

When we click the title link in the Listing page, we are redirected to Trial Description page (https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/v?id=NCI-2015-00054&r=1 ) with parameter r=1 instead of param rl=1. As a result we do not see the following text and link on the Trial Description page.
"This clinical trial matches: "all trials" | Start Over"
The link should be updated to use the "rl" parameter instead of "r".

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Go to https://www.cancer.gov/about-cancer/treatment/clinical-trials/intervention/trastuzumab?redirect=true
2. Click the first title link "Targeted Therapy Directed by Genetic Testing in Treating Patients with Advanced Refractory Solid Tumors, Lymphomas, or Multiple Myeloma (The MATCH Screening Trial)"
3. Notice that the url we are redirected to is (https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/v?id=NCI-2015-00054&r=1 with param r=1 instead of  param rl=1.

### What's the expected result?
- When we click a title link in the Listing pages we should be redirected to Trial Description page with param rl=1 in the url.
-  We should be able to see the following text and link on the Trial Description page
"This clinical trial matches: "all trials" | Start Over"

### What's the actual result?
- When we click a title link in the Listing pages we are redirected to Trial Description page with param r=1 in the url.
- We do not see the following text and link on the Trial Description page
"This clinical trial matches: "all trials" | Start Over"

### Additional details / screenshot
![image](https://user-images.githubusercontent.com/28455973/128536079-14e88fda-290c-4332-ab58-e1660fa93adb.png)

![image](https://user-images.githubusercontent.com/28455973/128536234-aee95936-ec82-4283-8585-179c74595b27.png)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by sarinapadilla** [comment]
This is an issue with the Clinical Trials Redirector - the parameter should be "redirect=true" rather than "r=1". Closing this ticket!
