### ISSUE TITLE
[Meta] Update Listing App to use CTS API v2

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/clinical-trials-listing-app#130]
This is an umbrella ticket to track all the tickets for updating the Clinical Trials Listing App to use CTS API v2.

### Tickets
- [x] #69 
- [x] #89 
- [x] #131
- [x] #88 
- [x] #129
- [x] #127 
- [x] #126 
- [x] #141

**Comment by sarinapadilla** [comment]
Closed because we use API v2!
