### ISSUE TITLE
Update v1 versions of variables to new V2 versions

### ISSUE THREAD

**Issue by alerosad** [NCIOCPL/clinical-trials-listing-app#135]
Description: 

In the v2 of the api, there were multiple changes made to variables such as:

The API endpoint now returns the data as 
{ 
	total: x,
	data: {},
}

Besides returning data in that new form, there is this schema change also:

{
  "central_contact": {
    "central_contact_phone": null,
    "central_contact_name": null,
    "central_contact_email": null,
    "central_contact_type": null
  }
}

 To:

{
  "central_contact": {
    "phone": null,
    "name": null,
    "type": null,
    "email": null
   }
}

Besides these two changes, there are many more listed in this document:
https://clinicaltrialsapi.cancer.gov/breaking-changes

All instances of these changed variables must be updated.

Parent Issue: 
Spike https://github.com/NCIOCPL/clinical-trials-listing-app/issues/127 

Sub-Tasks:

- [ ] Go through the breaking changes doc, and change variables accordingly.
- [ ] Update any tests accordingly

**Comment by sarinapadilla** [comment]
Closing this ticket as the update to CTS API v2 has been launched.
