### ISSUE TITLE
Update mocks to use v2 of CTS API

### ISSUE THREAD

**Issue by alerosad** [NCIOCPL/clinical-trials-listing-app#137]
Description:

The mocks need to use the newest version of CTS API

Parent Issue: 
Spike https://github.com/NCIOCPL/clinical-trials-listing-app/issues/127 

Sub-tasks:
- [ ] Go through and update the mocks to use v2 of the CTS API
- [ ] Check if any tests break, if so update accordingly

**Comment by sarinapadilla** [comment]
Closing this ticket as the update to CTS API v2 has been launched.
