### ISSUE TITLE
Update npm security vulnerabilities

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/clinical-trials-listing-app#152]
There are a number of security vulnerabilities that should be fixed via `npm audit fix`.

> **ESTIMATE** 2

### Notes
- This has the potential to break things as dependencies are updated to newer versions. Application functionality must be tested thoroughly.

**Comment by seyilonge-nci** [comment]
- An `npm audit` report generated the file attached below
[ctl-npm-audit-report-before.txt](https://github.com/NCIOCPL/clinical-trials-listing-app/files/9577219/ctl-npm-audit-report-before.txt)

- Ran `npm audit fix` successfully

- `npm run test` ran successfully with no errors

- Running `npm audit` generated file attached below
[cts-npm-audit-report-after.txt](https://github.com/NCIOCPL/clinical-trials-listing-app/files/9577224/cts-npm-audit-report-after.txt)
