### ISSUE TITLE
Update app to use Node 16 and npm 8

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/clinical-trials-listing-app#165]
### Issue description
Update the `engines` in package.json to the new versions, and update the GH workflow. We will also have to update package-lock.json to use the new npm format.

As part of this ticket, we need to update to the newest release of the `cgov-react-app-playground` shared workflow.

> **ESTIMATE** 2

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* React App Playground: https://github.com/NCIOCPL/cgov-react-app-playground/issues/74

**Comment by alerosad** [comment]
updating to node 16 gave me an error when trying to start the app:`Cannot find module 'react-dev-utils/getPublicUrlOrPath'`
