### ISSUE TITLE
Search fails when accessed from outside the US

### ISSUE THREAD

**Issue by MortenHofft** [NCIOCPL/clinical-trials-listing-app#187]
There should be am e2e test to ensure search works on the website

E.g. https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/r?loc=0&q=test&rl=1 
is broken on:
* firefox linux
* edge windows
* edge, forefox, chrome, edge on mac
* safari on ios

The error shows as a CORS header issue. Bad config? Perhaps location based? I'm in DK.

**Comment by bryanpizzillo** [comment]
@MortenHofft, I sorry to let you know I checked with the Clinical Trials API team and they do indeed block requests outside of Canada and USA. Their FAQ is located at https://clinicaltrialsapi.cancer.gov/faq is you would like to reach out to them to discuss your use case. I will be closing this ticket as the functionality works within USA and Canada per the API security requirements.

**Comment by MortenHofft** [comment]
Ideally the website would inform me about this issue, instead of a never ending loader.
