### ISSUE TITLE
Enabler: Make "page not found" status available to prerenderers for disease

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/clinical-trials-listing-app#21]
# Title of Enabler

When the application returns a "Page not found" message, the page should contain the markup:

```html
<meta name="prerender-status-code" content="404">
```

This will allow a pre-renderer to detect the error and report the correct 404 status code.

> **ESTIMATE** 1

### Resources:
* 

### Prerequisites
- 

### Sub-Tasks
- 

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

**Comment by VictoriaSunNIH** [comment]
Made part of ACs for 404 page
