### ISSUE TITLE
Spike: Investigate age and age range in CTS API

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/clinical-trials-listing-app#217]
To drive our decision on type of input for the Age filter, we need to investigate the CTS API for how trials are coded for age eligibility criteria.

If trials are often more specific in age, we will use a text input.
If trials are often in age ranges, we will consider using a checkbox list.

**Comment by adriancofie** [comment]
99 Years max

[response_1710856622993.json](https://github.com/NCIOCPL/clinical-trials-listing-app/files/14651506/response_1710856622993.json)

**Comment by sarinapadilla** [comment]
Based on the findings from @adriancofie, we're going to go ahead with the checkbox list of age ranges for the Age filter rather than a text input. The requirements on #206 have been updated!
