### ISSUE TITLE
Trial Listings for Manual not Filtered by Recruitment Status

### ISSUE THREAD

**Issue by seyilonge-nci** [NCIOCPL/clinical-trials-listing-app#28]
### Issue description
*Trial listing sites are not filtered by active recruitment status*
Only trial listing sites with recruitment status listed below should be displayed in results
 - active
 - approved
 - enrolling_by_invitation
 - in_review
 - temporarily_closed_to_accrual

> **ESTIMATE** 2

### Steps to reproduce the issue

1.  Go to https://www.cancer.gov/about-cancer/treatment/clinical-trials/adult-brain-tumors
2. Once results for clinical trials is displayed. Note `Location` in the results for title "***AQ4N in Combination With Radiotherapy and Temozolomide in Subjects With Newly Diagnosed Glioblastoma Multiforme***"
    > AQ4N in Combination With Radiotherapy and Temozolomide in Subjects With Newly Diagnosed Glioblastoma Multiforme
Phase 1b of the study, will evaluate the safety and tolerability of AQ4N treatment at three different dose levels. Phase 2a of the study, will further evaluate the safety, tolerability, and in addition efficacy of AQ4N treatment at a tolerated dose selected from Phase 1b.
Location: See Clinical Trials.gov
---
3. Open a new tab and go to https://react-app-dev.cancer.gov/clinical-trials-listing-app/pr-27?cfg=2 to compare results for the same title. Note the `Location` displayed as well
    > AQ4N in Combination With Radiotherapy and Temozolomide in Subjects With Newly Diagnosed Glioblastoma Multiforme
Phase 1b of the study, will evaluate the safety and tolerability of AQ4N treatment at three different dose levels. Phase 2a of the study, will further evaluate the safety, tolerability, and in addition efficacy of AQ4N treatment at a tolerated dose selected from Phase 1b.
Location: Duke University Medical Center, Durham, North Carolina 

### What's the expected result?
Carboplatin, Melphalan, Etoposide Phosphate, Mannitol, and Sodium Thiosulfate in Treating Patients With Previously Treated Brain Tumors
This phase I / II trial studies the side effects and best dose of melphalan when given together with carboplatin, etoposide phosphate, mannitol, and sodium thiosulfate and to see how well they work in treating patients with previously treated brain tumors. Drugs used in chemotherapy, such as melphalan, carboplatin, and etoposide phosphate, work in different ways to stop the growth of tumor cells, either by killing the cells or by stopping them from dividing, or by stopping them from spreading. Osmotic blood-brain barrier disruption (BBBD) uses mannitol to open the blood vessels around the brain and allow cancer-killing substances to be carried directly to the brain. Sodium thiosulfate may help lessen or prevent hearing loss and toxicities in patients undergoing chemotherapy with carboplatin and BBBD. Giving carboplatin, melphalan, etoposide phosphate, mannitol, and sodium thiosulfate together may be an effective treatment for brain tumors.
Location: OHSU Knight Cancer Institute, Portland, Oregon

Stereotactic Radiosurgery in Treating Patients with Brain Metastasis
This phase I trial studies the side effects and best dose of stereotactic radiosurgery (SRS) in treating patients with brain metastasis. Brain metastases are tumors that have spread to the brain from another place in the body. SRS is a specialized radiation therapy that delivers a single, high dose of radiation directly to the tumor and may kill more tumor cells and cause less damage to normal tissue.
Location: UT Southwestern / Simmons Cancer Center-Dallas, Dallas, Texas

AQ4N in Combination With Radiotherapy and Temozolomide in Subjects With Newly Diagnosed Glioblastoma Multiforme
Phase 1b of the study, will evaluate the safety and tolerability of AQ4N treatment at three different dose levels. Phase 2a of the study, will further evaluate the safety, tolerability, and in addition efficacy of AQ4N treatment at a tolerated dose selected from Phase 1b.
Location: See Clinical Trials.gov

EGFRBi-Armed Autologous T Cells in Treating Patients with Recurrent or Refractory Glioblastoma
This phase I / II trial studies the side effects and best dose of epidermal growth factor receptor bispecific antibody (EGFRBi)-armed autologous T cells and how well it works in treating patients with glioblastoma that have come back or does not respond to treatment. EGFRBi-armed autologous T cells coated with antibodies (proteins used by the immune system to target and kill foreign objects such as cancer cells) may have great ability to seek out, attach to, and destroy glioblastoma cells.
Location: Wayne State University / Karmanos Cancer Institute, Detroit, Michigan

### What's the actual result?
Carboplatin, Melphalan, Etoposide Phosphate, Mannitol, and Sodium Thiosulfate in Treating Patients With Previously Treated Brain Tumors
This phase I / II trial studies the side effects and best dose of melphalan when given together with carboplatin, etoposide phosphate, mannitol, and sodium thiosulfate and to see how well they work in treating patients with previously treated brain tumors. Drugs used in chemotherapy, such as melphalan, carboplatin, and etoposide phosphate, work in different ways to stop the growth of tumor cells, either by killing the cells or by stopping them from dividing, or by stopping them from spreading. Osmotic blood-brain barrier disruption (BBBD) uses mannitol to open the blood vessels around the brain and allow cancer-killing substances to be carried directly to the brain. Sodium thiosulfate may help lessen or prevent hearing loss and toxicities in patients undergoing chemotherapy with carboplatin and BBBD. Giving carboplatin, melphalan, etoposide phosphate, mannitol, and sodium thiosulfate together may be an effective treatment for brain tumors.
Location: 2 Locations

Stereotactic Radiosurgery in Treating Patients with Brain Metastasis
This phase I trial studies the side effects and best dose of stereotactic radiosurgery (SRS) in treating patients with brain metastasis. Brain metastases are tumors that have spread to the brain from another place in the body. SRS is a specialized radiation therapy that delivers a single, high dose of radiation directly to the tumor and may kill more tumor cells and cause less damage to normal tissue.
Location: UT Southwestern / Simmons Cancer Center-Dallas, Dallas, Texas

AQ4N in Combination With Radiotherapy and Temozolomide in Subjects With Newly Diagnosed Glioblastoma Multiforme
Phase 1b of the study, will evaluate the safety and tolerability of AQ4N treatment at three different dose levels. Phase 2a of the study, will further evaluate the safety, tolerability, and in addition efficacy of AQ4N treatment at a tolerated dose selected from Phase 1b.
Location: Duke University Medical Center, Durham, North Carolina

EGFRBi-Armed Autologous T Cells in Treating Patients with Recurrent or Refractory Glioblastoma
This phase I / II trial studies the side effects and best dose of epidermal growth factor receptor bispecific antibody (EGFRBi)-armed autologous T cells and how well it works in treating patients with glioblastoma that have come back or does not respond to treatment. EGFRBi-armed autologous T cells coated with antibodies (proteins used by the immune system to target and kill foreign objects such as cancer cells) may have great ability to seek out, attach to, and destroy glioblastoma cells.
Location: Wayne State University / Karmanos Cancer Institute, Detroit, Michigan

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by alinai** [comment]
Space is missing between "Clinical" and "Trials" in the Location: See Clinical Trials.gov link.
![image](https://user-images.githubusercontent.com/28455973/109201106-6c7ae280-776f-11eb-84e4-76204d085c5a.png)

**Comment by alinai** [comment]
@mworrest , can you please confirm if the spacing between the trial description and location looks good to you?

**Comment by alinai** [comment]
Rest looks good to me. Thanks @seyilonge-nci and @alerosad!

**Comment by mworrest** [comment]
Looks good to me.

**Comment by alinai** [comment]
Thanks @mworrest for confirming.
