### ISSUE TITLE
Spike: Fetch Caching

### ISSUE THREAD

**Issue by seyilonge-nci** [NCIOCPL/clinical-trials-listing-app#47]
## In order to <achieve some goal> <a system or persona> needs to <some action>.

*Examples:*
* *In order to split the collection curve wizard story, the tech lead needs to do some detailed design. (Just enough to split the story.)*
* *In order to estimate the content task story, the PO needs to do identify how many pages are affected. (Just detailed enough to estimate the story.)*

> **Estimate** 3

***NOTE: a single story point is about 1 day.  A spike should not go on for more than 2 days, otherwise it is too big, or it needs to be an enabler and estimated.***

Look into caching for fetch calls using react-fetching-library

### Expected Deliverables:
Example code to implement, as well as a demo

### Additional Notes:
* note 1

### Results of Spike
*Enter the information, or links to any (non-sensative) files with the findings here*

**Comment by VictoriaSunNIH** [comment]
Taken care of as part of refactoring code in #63
