### ISSUE TITLE
Boost CTLViewsHoC Coverage

### ISSUE THREAD

**Issue by alerosad** [NCIOCPL/clinical-trials-listing-app#58]
*Boost CTLViewsHoC Coverage to 100%*

### Sub-Tasks
- [ ] Add Unit test for condition when PrettyURL is specified

### Notes

*Some complementary notes if necessary:*
* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

**Comment by VictoriaSunNIH** [comment]
Closing as completed as part of #63
