### ISSUE TITLE
Remove React App Fetching from Trial Requests

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/clinical-trials-listing-app#69]
### Issue description
React fetching library is not scaling well for us, it has been removed for listing lookups, and should be removed for trial look ups. (This should follow the pattern we did for useListingSupport & the HoC)

So we should:
1. Create an Axios instance setting the base url to the passed in API base
2. Add the Axios instance to a var on the application's state. Maybe something like:
    ```
    const initialState = {
       apiClients: {
          ctsapi: <your_instance>
       }
    }
    ``` 
3. Create helper functions for each of your endpoint calls, passing an axios instance as the first parameter. These will be async functions, and do the actual call to the API. Throw an Error on errors, return the valid payload on response.
4. Create a hook for handling the `useCtsApi`. This will:
    1. Take in an action with the params for the search.
    2. This hook will get the axios clients from the app state
    3. It will then use the helper functions 
    4. It will return an object with 4 state variables: loading, error, payload and abort. (you will set loading to true at the start, and the other vars in either your catch or after the await.)
    5. NOTE: Please follow the pattern of isMounted and useCallback introduced in useListingSupport - these things guard against an infinite number of requests.
5. Update the various views (Disease, Intervention, Disease + type, Intervention + type, Disease + type + intervention) to call this useCtsApi hook instead of the customFetch.
6. Remove all the old actions, the interceptor config and any other references to react-fetching-library. This also includes useCustomQuery.

> **ESTIMATE** TBD

### What's the expected change?
- Code changes, code works, code can scale

### What's the current functionality?
-

### What's the updated acceptance criteria?
```gherkin
```

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

**Comment by VictoriaSunNIH** [comment]
We should hold off on this story until we update the app to use CTS API V2
