### ISSUE TITLE
At tablet and mobile breakpoint, double horizontal rule should not be displayed at the top when pager does not show up. (Manual)

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/clinical-trials-listing-app#75]
### Issue description
See #71 

Make these changes on the release branch release/v1.0.0

> **ESTIMATE** 2

### Steps to reproduce the issue

1.  
2. 
3. 

### What's the expected result?
-

### What's the actual result?
-

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by KateMashkinaNIH** [comment]
this had been merged
