### ISSUE TITLE
Scroll position should not be maintained when paging through (DLP)

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/clinical-trials-listing-app#83]
### Issue description

Paging through should always bring user to the top of a page

At desktop, we return to the top of the H1 title not the top of the NIH header when we click any page link (pn=3) from bottom pager. At mobile and tablet, the position is maintained and we do not return to the top of the page consistently. Also, if we scroll a bit down and page through the top pager, it stays where we are.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1. Go to https://react-app-dev.cancer.gov/clinical-trials-listing-app/develop/breast-cancer?cfg=0
2. Scroll a bit down and page through the top pager 
3. It stays where we are and we do not return to the top of the page
4. Scroll all the way down to the bottom pager.
5. Click any page link (e.g pn=5) 
6. We return to the top of the H1 title not the top of the NIH header
7. Switch to tablet breakpoint
8. Click any page link (e.g pn=7) 
9. We do not return to the top of the page

### What's the expected result?
- We should be returning to the top of the page when we page through the top page or bottom pager.

### What's the actual result?
- It stays where we are

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by KateMashkinaNIH** [comment]
this has already been implemented as part of AC for  all disease routes. Intervention paths will also taken off when pr#99 is merged

**Comment by santwuma** [comment]
issue fixed and will go into effect once pr#99 is merged
