### ISSUE TITLE
App should maintain scroll position when hitting a back arrow in the browser 

### ISSUE THREAD

**Issue by KateMashkinaNIH** [NCIOCPL/clinical-trials-listing-app#86]
### Issue description
*Description of the issue*
ODE - clicking a trial link and then hitting back arrow should bring user back to where user left it  - currently it only maintains the scroll position in safari, other browsers show inconsistent behavior.

https://ncigovcdode417.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/cam-procedures/?pn=2

> **ESTIMATE** 3

### Steps to reproduce the issue

1.  
2. 
3. 

### What's the expected result?
-

### What's the actual result?
-

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by KateMashkinaNIH** [comment]
this issue was half fixed - pagination works as expected, however the back button behavior is still inconsistent across all browsers ( TBH it is also inconsistent in the SWS app and I suspect in others) 

this was deemed a low priority and should stay  as a back log item

**Comment by KateMashkinaNIH** [comment]
Reopening this as the back arrow issue still exists in both Manual and Dynamic listing pages

**Comment by bryanpizzillo** [comment]
Some additional notes based on a call:
1. There are MULTIPLE scenarios of handling scroll position, that have not been enumerated here. @seyilonge-nci is going to attach a table here with the scenarios.
2. There is a bug in the pager logic where we replace the history. So you cannot hit back buttons for the pager. This would also add a new scenario to the list above. @seyilonge-nci  is going to create that ticket.
3. Scroll Position Information:
   1. The app loads before any of the www nonsense runs, this includes the sticky headers.
   2. Sticky headers when active are detatched from the page and float at the top -- this means that 0,0 is not the top of the page in some cases.  
   4. When the back button is pressed, at least in chrome, the sticky nav and such appears to be active and thus postion 0,0 will be UNDER the sticky header showing at that time.
       * We need a param of some sorts passed into the app to know what the top offset is. This is tricky, cause the sticky nav has three different height positions on desktop. One for at the top of the page, one for downward motion when not at top, and one for upward motion when not at top. So it is not a single value. 
4. @arcepaul  pointed out that the browser history can also have state stored with it, i.e. the scroll position. So the app could be updated to handle the scroll position that we left that page in. On reload we scroll to the position with the associated state. I am sure this will have more issues that we have not enumerated here.

**Comment by seyilonge-nci** [comment]
> Some additional notes based on a call:
> 
> 1. There are MULTIPLE scenarios of handling scroll position, that have not been enumerated here. @seyilonge-nci is going to attach a table here with the scenarios.
> 2. There is a bug in the pager logic where we replace the history. So you cannot hit back buttons for the pager. This would also add a new scenario to the list above. @seyilonge-nci  is going to create that ticket.
> 3. Scroll Position Information:
>    
>    1. The app loads before any of the www nonsense runs, this includes the sticky headers.
>    2. Sticky headers when active are detatched from the page and float at the top -- this means that 0,0 is not the top of the page in some cases.
>    3. When the back button is pressed, at least in chrome, the sticky nav and such appears to be active and thus postion 0,0 will be UNDER the sticky header showing at that time.
>       
>       * We need a param of some sorts passed into the app to know what the top offset is. This is tricky, cause the sticky nav has three different height positions on desktop. One for at the top of the page, one for downward motion when not at top, and one for upward motion when not at top. So it is not a single value.
> 4. @arcepaul  pointed out that the browser history can also have state stored with it, i.e. the scroll position. So the app could be updated to handle the scroll position that we left that page in. On reload we scroll to the position with the associated state. I am sure this will have more issues that we have not enumerated here.

Table with scenarios below as mentioned in item 1 above

| Initial Scroll Position  | Action  | Expected Scroll Position  |
|---|---|---|
| Top  | Browser Back Button  | Top  |
| Middle  | Browser Back Button  | Middle  |
| Bottom  | Browser Back Button  | Bottom  |
|   |   |   |
| Top  | Pager Navigation  | Top  |
| Middle  | Pager Navigation  | Top  |
| Bottom  | Pager Navigation  | Top  |

**Comment by VictoriaSunNIH** [comment]
@seyilonge-nci - these scenarios all look right to me. For "middle" does this mean that the back button would return the user to wherever the user scrolled to somewhere in the middle of the page?

**Comment by seyilonge-nci** [comment]
@VictoriaSunNIH Yes, that's correct.
