### ISSUE TITLE
Use our Github actions to deploy to Netstorage

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/clinical-trials-listing-app#88]
### Issue description
Deploying the built site to netstorage for testing is a bit of a mess with an entire Python script to accomplish this. Furthermore automating deployments to production netstorage would require ANOTHER full python script. So lets use https://github.com/NCIOCPL/netstorage-upload-action to upload, and https://github.com/NCIOCPL/akamai-purge-action to clear the cache.

> **ESTIMATE** TBD

### What's the expected change?
- Python in GH actions goes away, and is replaced by this one little known action.
- No actual changes to process should occur.

See https://github.com/NCIOCPL/cgov-react-app-playground/issues/29 for specific changes.

**Comment by sarinapadilla** [comment]
Closing this ticket as it was completed as part of this [ticket](https://github.com/NCIOCPL/cgov-react-app-playground/issues/29) / [this PR](https://github.com/NCIOCPL/cgov-react-app-playground/pull/31) in `cgov-react-app-playground`.
