### ISSUE TITLE
[REMOVE] Story: Metadata for Listing Pages

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/clinical-trials-listing-app#9]
## As a user, I want metadata on the page, so that I can share the web page to social media services correctly.

> **ESTIMATE** 2 / 3

The metadata for the disease and intervention listing pages is set according to the given parameters.

#### Disease
Title: [Disease Name] Clinical Trials - National Cancer Institute
Og title: [Disease Name] Clinical Trials - National Cancer Institute
Og url: [base host]/disease/[disease-friendly-name]
Description: "NCI supports clinical trials studying new and more effective ways to detect and treat cancer. Find clinical trials for [disease name]."
Canonical URL: [canonical-host]/disease/[disease-friendly-name]

#### Disease, Trial Type
Title: [Trial Type] Clinical Trials for [Disease Name] - National Cancer Institute
Og title: [Trial Type] Clinical Trials for [Disease Name] - National Cancer Institute
Og url: [base host]/disease/[disease-friendly-name]/[trial-type]
Description: "NCI supports clinical trials studying new and more effective ways to detect and treat cancer. Find [trial type] clinical trials for [disease name]."
Canonical URL: [canonical-host]/disease/[disease-friendly-name]/[trial-type]

#### Disease, Trial Type, Intervention
Title: [Trial Type] Clinical Trials for [Disease Name] Using [Intervention Name] - National Cancer Institute
Og title: [Trial Type] Clinical Trials for [Disease Name] Using [Intervention Name] - National Cancer Institute
Og url: [base host]/disease/[disease-friendly-name]/[trial-type]/[intervention-friendly-name]
Description: "NCI supports clinical trials studying new and more effective ways to detect and treat cancer. Find clinical trials testing [intervention name] in the [trial type] of [disease name]."
Canonical URL: [canonical-host]/disease/[disease-friendly-name]/[trial-type]/[intervention-name]

#### Intervention
Title: Clinical Trials Using [Intervention Name] - National Cancer Institute
Og title: Clinical Trials Using [Intervention Name] - National Cancer Institute
Og url: [base host]/intervention/[intervention-friendly-name]
Description: "NCI supports clinical trials studying new and more effective ways to detect and treat cancer. Find clinical trials studying [intervention name]."
Canonical URL: [canonical-host]/intervention/[intervention-friendly-name]

#### Intervention, Trial Type
Title: [Trial Type] Clinical Trials Using [Intervention Name] - National Cancer Institute
Og title: [Trial Type] Clinical Trials Using [Intervention Name] - National Cancer Institute
Og url: [base host]/disease/[disease-friendly-name]/[trial-type]
Description: "NCI supports clinical trials studying new and more effective ways to detect and treat cancer. Find clinical trials testing [trial type] methods that use [intervention name].""
Canonical URL: [canonical-host]/intervention/[intervention-friendly-name]/[trial-type]

#### Disease pages:
```gherkin
Scenario: View disease dynamic listing page metadata with disease parameter only
  Given the user is viewing the dynamic listing page for disease "breast cancer"
  When the site name is "National Cancer Institute"
     And the canonical host is "https://www.cancer.gov"
     And the base host is "http://localhost:3000"
     And the base path is ""
  Then the title tag should be "Breast Cancer Clinical Trials - National Cancer Institute" 
    And there is a meta tag with a property "og:title" and content "Disease Dynamic Trial Listing Page"
    And there is a meta tag with a property "og:url" and content "http://localhost:3000/disease/breast-cancer"
    And there is a meta tag with a property "description" and content "NCI supports clinical trials studying new and more effective ways to detect and treat cancer. Find clinical trials for breast cancer."
    And there is a link tag with rel "canonical" and href  "https://www.cancer.gov/disease/breast-cancer"
```

```gherkin
Scenario: View disease dynamic listing page metadata with disease and trial type parameters
  Given the user is viewing the dynamic listing page for disease "breast cancer" and trial type "treatment"
  When the site name is "National Cancer Institute"
     And the canonical host is "https://www.cancer.gov"
     And the base host is "http://localhost:3000"
     And the base path is ""
  Then the title tag should be "Treatment Clinical Trials for Breast Cancer - National Cancer Institute" 
    And there is a meta tag with a property "og:title" and content "Disease Dynamic Trial Listing Page"
    And there is a meta tag with a property "og:url" and content "http://localhost:3000/disease/breast-cancer/treatment"
    And there is a meta tag with a property "description" and content "NCI supports clinical trials studying new and more effective ways to detect and treat cancer. Find treatment clinical trials for breast cancer."
    And there is a link tag with rel "canonical" and href  "https://www.cancer.gov/disease/breast-cancer/treatment"
```

```gherkin
Scenario: View disease dynamic listing page metadata with disease, trial type, and intervention parameters
  Given the user is viewing the dynamic listing page for disease "breast cancer", trial type "treatment", and intervention "trastuzumab"
  When the site name is "National Cancer Institute"
     And the canonical host is "https://www.cancer.gov"
     And the base host is "http://localhost:3000"
     And the base path is ""
  Then the title tag should be "Treatment Cancer Clinical Trials for Breast Cancer Using Trastuzumab - National Cancer Institute" 
    And there is a meta tag with a property "og:title" and content "Disease Dynamic Trial Listing Page"
    And there is a meta tag with a property "og:url" and content "http://localhost:3000/disease/breast-cancer/treatment/trastuzumab"
    And there is a meta tag with a property "description" and content "NCI supports clinical trials studying new and more effective ways to treat cancer. Find clinical trials testing trastuzumab in the treatment of breast cancer."
    And there is a link tag with rel "canonical" and href  "https://www.cancer.gov/disease/breast-cancer/treatment/trastuzumab"
```

#### Intervention pages:
```gherkin
Scenario: View intervention dynamic listing page metadata with intervention parameter only
  Given the user is viewing the dynamic listing page for intervention "trastuzumab"
  When the site name is "National Cancer Institute"
     And the canonical host is "https://www.cancer.gov"
     And the base host is "http://localhost:3000"
     And the base path is ""
  Then the title tag should be "Clinical Trials Using Trastuzumab - National Cancer Institute" 
    And there is a meta tag with a property "og:title" and content "Intervention Dynamic Trial Listing Page"
    And there is a meta tag with a property "og:url" and content "http://localhost:3000/intervention/trastuzumab"
    And there is a meta tag with a property "description" and content "NCI supports clinical trials that test new and more effective ways to treat cancer. Find clinical trials studying trastuzumab."
    And there is a link tag with rel "canonical" and href  "https://www.cancer.gov/intervention/trastuzumab"
```

```gherkin
Scenario: View intervention dynamic listing page metadata with intervention and trial type parameters
  Given the user is viewing the dynamic listing page for intervention "trastuzumab" and trial type "treatment"
  When the site name is "National Cancer Institute"
     And the canonical host is "https://www.cancer.gov"
     And the base host is "http://localhost:3000"
     And the base path is ""
  Then the title tag should be "Treatment Clinical Trials Using Trastuzumab - National Cancer Institute" 
    And there is a meta tag with a property "og:title" and content "Intervention Dynamic Trial Listing Page"
    And there is a meta tag with a property "og:url" and content "http://localhost:3000/intervention/trastuzumab/treatment"
    And there is a meta tag with a property "description" and content "NCI supports clinical trials studying new and more effective ways to treat cancer. Find clinical trials testing treatment methods that use trastuzumab."
    And there is a link tag with rel "canonical" and href  "https://www.cancer.gov/intervention/trastuzumab/treatment"
```

### Resources:
* Web Pages:
    * Disease:
        * view-source:https://www.cancer.gov/about-cancer/treatment/clinical-trials/disease/breast-cancer
        * view-source:https://www.cancer.gov/about-cancer/treatment/clinical-trials/disease/breast-cancer/treatment
        * view-source:https://www.cancer.gov/about-cancer/treatment/clinical-trials/disease/breast-cancer/treatment/trastuzumab
    * Intervention:
        * view-source:https://www.cancer.gov/about-cancer/treatment/clinical-trials/intervention/trastuzumab
        * view-source:https://www.cancer.gov/about-cancer/treatment/clinical-trials/intervention/trastuzumab/treatment

### Notes
See below document for more detailed information about metadata on dynamic listing pages.
[DLP-Metadata.docx](https://github.com/NCIOCPL/clinical-trials-listing-app/files/5798003/DLP-Metadata.docx)

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

**Comment by sarinapadilla** [comment]
This story has been broken into tasks for each of the five different dynamic listing page patterns.
