### ISSUE TITLE
Set up configs for each of the existing manual pages

### ISSUE THREAD

**Issue by KateMashkinaNIH** [NCIOCPL/clinical-trials-listing-app#90]
*Description of what is to be accomplished.*

Each manual page will have to be manually created in Drupal on the ODE ( example here : https://ncigovcdode417.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/adult-brain-tumors ) by following instructions here https://nih.app.box.com/file/802768706583
**Parent Issue:** #9999

### Sub-Tasks
- [ ] Point ODE to the MLP adobe analytics library 
- [ ] clear cache
- [ ] Test each page
### Notes

*Some complementary notes if necessary:*
* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

**Comment by VictoriaSunNIH** [comment]
completed and launched!
