### ISSUE TITLE
Implement Caching for Trial Type Fetch

### ISSUE THREAD

**Issue by seyilonge-nci** [NCIOCPL/clinical-trials-listing-app#92]
### Need to cache Trial Type fetch results returned from an API call
*Description of the issue*

> **ESTIMATE** 2

### What's the expected change?
- Updated `useListingSupport` to support caching for Trial Type

### What's the current functionality?
- Trial Type fetches are not cached and could result in unwanted multiple network requests

### What's the updated acceptance criteria?
```gherkin
```

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

**Comment by santwuma** [comment]
Duplicate of story #48 . Added an additional task and increased SPs to story #48 to cover this story.
