### ISSUE TITLE
Intro text should be present at all times and not wait for page to fully load (Manual)

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/clinical-trials-listing-app#93]
### Issue description
*Description of the issue*

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Go to https://www-dev-acsf.cancer.gov/about-cancer/treatment/clinical-trials/covid-19
2. Click pn=2
3. The intro text disappears until the page is loaded

### What's the expected result?
- The intro text should always be present on a page once page is loaded and not depend on page load while paging 

### What's the actual result?
-The intro text disappears until page is loaded when paging through.

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by alinai** [comment]
1. Intro text disappearing on pagination issue is resolved on https://ncigovcdode417.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/covid-19/?pn=2
2. The semi-colon is no longer appearing in the pager area. (https://ncigovcdode417.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/childhood-embryonal-tumors)
3. The delighters appears in both pages but **we need to verify if we want it to appear in the position it appears at mobile breakpoint.**

**Comment by sarinapadilla** [comment]
This issue has been fixed by #98 , so closing this ticket.
