### ISSUE TITLE
Listing apps should accommodate for delighter

### ISSUE THREAD

**Issue by kate-mashkina** [NCIOCPL/clinical-trials-listing-app#95]
### Issue description
*Description of the issue*
Currently both manual and dynamic pages do not have page options as it was removed intentionally - which caused drupal not render delighter.

The solution is to add an empty page options block to both apps

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  
2. 
3. 

### What's the expected result?
-

### What's the actual result?
-

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by VictoriaSunNIH** [comment]
Create a hotfix branch off of main for this. @arcepaul please add an approach

**Comment by KateMashkinaNIH** [comment]
previous  approach did not work - currently pr https://github.com/NCIOCPL/clinical-trials-listing-app/pull/98 is taking care of this issue
